env:
  browser: true
  #extends: 'eslint:recommended'
extends: ['prettier']
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
